// SPDX-License-Identifier: MIT
// Copyright (c) @jeanmajid & Contributors
// Contributors: @jeanmajid
// See LICENSE.md file in the root folder, licenses/MIT.md, or https://opensource.org/license/mit

export const enum ItemId {
    cancelGame = "bcc.cook:cancel_game",
    exitLobby = "bcc.cook:exit_lobby",
    mapSelector = "bcc.cook:map_selector",
    statsViewer = "bcc.cook:stats_viewer",
	fireExtinguisher = "bcc.cook:fire_extinguisher",
    getBlockData = "bcc.cook:get_block_data",
    getItemBlockData = "bcc.cook:get_item_block_data",
    boba = "bcc.cook:boba",
    soySauce = "bcc.cook:soy_sauce",
    vinegar = "bcc.cook:vinegar",
    burgerBun = "bcc.cook:burger_bun",
    cabbage = "bcc.cook:cabbage",
    cabbageLeaf = "bcc.cook:cabbage_leaf",
    carrot = "bcc.cook:carrot",
    celery = "bcc.cook:celery",
    cheese = "bcc.cook:cheese",
    cheeseSlice = "bcc.cook:cheese_slice",
    choppedGarlic = "bcc.cook:chopped_garlic",
    cookedBeefPatty = "bcc.cook:beef_patty.cooked",
    cookedChickenBits = "bcc.cook:chicken_bits.cooked",
    cookedNoodles = "bcc.cook:noodles.cooked",
    cookedOnionRings = "bcc.cook:onion_rings.cooked",
    cookedRice = "bcc.cook:rice.cooked",
    dicedCarrot = "bcc.cook:carrot.diced",
    dicedCelery = "bcc.cook:celery.diced",
    dough = "bcc.cook:dough",
    rawNoodles = "bcc.cook:noodles.raw",
    egg = "bcc.cook:egg",
    garlic = "bcc.cook:garlic",
    lettuce = "bcc.cook:lettuce",
    lettuceLeaf = "bcc.cook:lettuce_leaf",
    milk = "bcc.cook:milk",
    onion = "bcc.cook:onion",
    rawOnionRings = "bcc.cook:onion_rings.raw",
    rawBeefPatty = "bcc.cook:beef_patty.raw",
    rawChickenBits = "bcc.cook:chicken_bits.raw",
    rawMeatballs = "bcc.cook:meatballs.raw",
    rawRice = "bcc.cook:rice.raw",
    tapiocaPearls = "bcc.cook:tapioca_pearls",
    tomato = "bcc.cook:tomato",
    tomatoSlice = "bcc.cook:tomato_slice",
}