import { startingMap } from "../map.js";
import { vegetableSoupRecipe } from "../../../../constants/recipes/western/vegetableSoup.js";
import { tomatoSoupRecipe } from "../../../../constants/recipes/western/tomatoSoup.js";
import { spaghettiMeatballsRecipe } from "../../../../constants/recipes/western/spaghettiMeatballs.js";
import { simpleSpaghettiRecipe } from "../../../../constants/recipes/western/simpleSpaghetti.js";
import { simplePastaCarbonaraRecipe } from "../../../../constants/recipes/western/simplePastaCarbonara.js";
startingMap.recipeManager.addRecipe(simplePastaCarbonaraRecipe);
startingMap.recipeManager.addRecipe(simpleSpaghettiRecipe);
startingMap.recipeManager.addRecipe(spaghettiMeatballsRecipe);
startingMap.recipeManager.addRecipe(tomatoSoupRecipe);
startingMap.recipeManager.addRecipe(vegetableSoupRecipe);
